CREATE TABLE REGISTRODEPONTO(
	Id int IDENTITY(1,1) NOT NULL,
	Nome nvarchar(250) NULL,
	Cpf nvarchar(14) NULL,
	DataDoRegistro datetime2(7) NOT NULL,
	TipoDeRegistro int NOT NULL
)
ALTER TABLE REGISTRODEPONTO ADD CONSTRAINT [PK_REGISTRODEPONTO] PRIMARY KEY CLUSTERED (Id ASC)
GO


